### PR TITLE
Embark windows terminal

### PR DESCRIPTION
**Pull request by smithbm2316**
Added the embark.json file and updated the README.md with instructions

### CODE REVIEW

**Comment by icy-comet** [comment]
why hasn't this PR been merged? @smithbm2316

**Comment by smithbm2316** [comment]
@icy-comet I do not have access to merge. I'm not sure if the maintainer is still interested in this update. I do not use Windows at all anymore so I'm not totally sure that this PR still works the way that it's supposed to for Windows Terminal after how much time it's been

**Comment by icy-comet** [comment]
@smithbm2316  I didn't realize you weren't the maintainer, since the repo's  under GH organization. The theme works perfectly though.

**Comment by skbolton** [comment]
This slipped through the cracks, sorry @smithbm2316 when I moved to the organization notifications became a mess for me. Its possible the highlights in this PR are a little behind but I will merge and get it up to date. Or @icy-comet if you are interested in helping make sure the highlights are current I would appreciate any support.

**Comment by smithbm2316** [comment]
My GitHub notifications have been a mess for years @skbolton so no worries! 😄 I haven't used a windows machine for probably 2 years now, but hope that this still works well for those who use windows terminal. I love the embark theme, I just am not on a windows machine anymore to verify if it still looks the same 🙂

**Pull request merged**
